### PR TITLE
Added midi connect and disconnect scripts. Moved setup files to their own folder. Added pkill to M8_pulse.sh

### PR DESCRIPTION
**Pull request by smootalicious**

### CODE REVIEW

**Comment by smootalicious** [comment]
Made pkill more selective for pulseaudio process.

**Comment by smootalicious** [comment]
Removed the SDL configs. Works with bug fixed m8c awaiting PR review. See my m8c fork.

**Comment by jasonporritt** [comment]
This all works great for me. I tried adding the SDL controller configs to the m8c config file before trying the environment variable approach but I must have done something incorrectly since it didn't work. This combined with the m8c PR work great though. Nice!

**Comment by smootalicious** [comment]
You didn't do anything incorrectly, m8c just has a bug regarding gamecontroller enumeration.

**Pull request merged**
